{% set name = "databroker" %}
{% set version = "0.11.0" %}
{% set sha256 = "4c5da6cf81350209cddf95e3f597bd3bfe892af28e8c58ab55d77c6072d058d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - attrs >=16.3.0
    - boltons
    - cytoolz
    - doct
    - h5py
    - humanize
    - jsonschema
    - jinja2
    - mongoquery
    - numpy
    - pandas
    - pims
    - python
    - pytz
    - pyyaml
    - requests
    - six
    - tifffile
    - tornado
    - tzlocal
    - ujson

test:
  imports:
    - databroker
    - databroker.core
    - databroker.broker

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A unified interface to the various data sources at NSLS-II.'

  description: 'A unified interface to the various data sources at NSLS-II.'
  doc_url: http://nsls-ii.github.io/databroker/
  dev_url: https://github.com/NSLS-II/databroker/

extra:
  recipe-maintainers:
    - CJ-Wright
