travis:
  secure:
    BINSTAR_TOKEN: pGX/5gOg+0mLBvA6+r3xOHakfHNz/rLBjEvOehlShzVsSH8MqZMz8vRnkO0dADTYrmHOBF6TlCpP8sHRaETokDRj3FedJB/n2ONEmBTiMeLO95QVqgkOwXXBjYfg5f7EDQjfHSsboOIXPq9jM1v+rR51cgjKXanC9K124Znia+5gPBhgcV3Hoer3k9ZH5Wsv1DNBVEK3m3wFFUZEad5MgkUwTU9ywcbP96/m6JfZLAK4RHBfJVg5L9+jdIsrnWLnI2VK/YxHu0AoXQVb4mj34CvEdCJQcARUWH8axGN9nueSKtNmSIgwWYPsij1VUnYMIyc4WbphhcoEH0QkdMaBUBQT5zniKeV3ymrBc/40p6U81R4gkCB4faYWje0dj9ahgMH1TXsBxw3Oa2pEBI3/wp3EaUyiuV2QoYruqhWcrltQoZn+7NgBvtkUd+v9VYEDW6ez6Yb2+HlRHRWqGmLIdYGVzCfClP2BhbUGgW9kQnnq6gMBS7EcfoPtb4O3Odo9BZrx+nnmiPVgD9X5+D8p8n4fiT8POPSKZmRrDChtcfFRiR/XFSerils3GNqxLXdWzGQr/IZh2JZuhIZYgstggTCgrIDZmh1wo9KV+DgRN5bj4DH7CjUQdtpbwP7fBa9UkY+qoyMvAEEEaWd2GX4LTga8pZIGmPpE3pcUxF+0B78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
